import type { CuratedLink } from './types.ts';

export const catalog: CuratedLink[] = [
  {
    id: 'mdn-web',
    title: 'MDN Web Docs',
    url: 'https://developer.mozilla.org/en-US/docs/Web',
    description: 'Authoritative documentation for web technologies, browser APIs, and standards.',
    category: 'browser-apis',
    tags: ['documentation', 'apis', 'standards'],
    official: true,
    featured: true,
  },
  {
    id: 'web-dev',
    title: 'web.dev',
    url: 'https://web.dev/',
    description: 'Guidance on modern web development, performance, and platform capabilities.',
    category: 'browser-apis',
    tags: ['guides', 'performance', 'apis'],
    official: true,
    featured: true,
  },
  {
    id: 'caniuse',
    title: 'Can I use',
    url: 'https://caniuse.com/',
    description: 'Browser support tables for web platform features across engines.',
    category: 'browser-apis',
    tags: ['compatibility', 'support'],
    official: false,
  },
  {
    id: 'w3c-spec',
    title: 'W3C Standards',
    url: 'https://www.w3.org/standards/',
    description: 'Official web standards and specifications from the World Wide Web Consortium.',
    category: 'browser-apis',
    tags: ['standards', 'specifications'],
    official: true,
  },
  {
    id: 'ts-handbook',
    title: 'TypeScript Handbook',
    url: 'https://www.typescriptlang.org/docs/handbook/intro.html',
    description: 'Official TypeScript language documentation and learning resource.',
    category: 'typescript',
    tags: ['typescript', 'documentation'],
    official: true,
    featured: true,
  },
  {
    id: 'ts-playground',
    title: 'TypeScript Playground',
    url: 'https://www.typescriptlang.org/play/',
    description: 'Interactive editor to experiment with TypeScript and see compiler output.',
    category: 'typescript',
    tags: ['typescript', 'playground'],
    official: true,
  },
  {
    id: 'web-perf-google',
    title: 'Web Performance — Google Developers',
    url: 'https://developers.google.com/web/fundamentals/performance',
    description: 'Foundational performance concepts, metrics, and optimization techniques.',
    category: 'performance',
    tags: ['performance', 'metrics', 'optimization'],
    official: true,
    featured: true,
  },
  {
    id: 'web-vitals',
    title: 'Web Vitals',
    url: 'https://web.dev/vitals/',
    description: 'Core user-centric performance metrics: LCP, INP, and CLS.',
    category: 'performance',
    tags: ['metrics', 'core-web-vitals'],
    official: true,
  },
  {
    id: 'perf-calendar',
    title: 'PerfCalendar',
    url: 'https://www.perfplanet.com/',
    description: 'Annual performance community articles and benchmarking insights.',
    category: 'performance',
    tags: ['performance', 'community'],
    official: false,
  },
  {
    id: 'a11y-project',
    title: 'The A11Y Project',
    url: 'https://www.a11yproject.com/',
    description: 'Community-driven accessibility resources, checklists, and how-tos.',
    category: 'accessibility',
    tags: ['accessibility', 'a11y'],
    official: false,
    featured: true,
  },
  {
    id: 'wcag',
    title: 'WCAG 2.2',
    url: 'https://www.w3.org/WAI/WCAG22/quickref/',
    description: 'Quick reference for Web Content Accessibility Guidelines success criteria.',
    category: 'accessibility',
    tags: ['wcag', 'standards'],
    official: true,
  },
  {
    id: 'axe-core',
    title: 'axe-core',
    url: 'https://github.com/dequelabs/axe-core',
    description: 'Open-source accessibility testing engine used in many developer tools.',
    category: 'accessibility',
    tags: ['testing', 'a11y'],
    official: false,
  },
  {
    id: 'vitest',
    title: 'Vitest',
    url: 'https://vitest.dev/',
    description: 'Fast unit testing framework powered by Vite.',
    category: 'testing',
    tags: ['testing', 'vitest', 'vite'],
    official: true,
    featured: true,
  },
  {
    id: 'playwright',
    title: 'Playwright',
    url: 'https://playwright.dev/',
    description: 'Cross-browser end-to-end testing for modern web applications.',
    category: 'testing',
    tags: ['testing', 'e2e'],
    official: true,
  },
  {
    id: 'testing-library',
    title: 'Testing Library',
    url: 'https://testing-library.com/',
    description: 'Testing utilities focused on user-visible behavior rather than implementation.',
    category: 'testing',
    tags: ['testing', 'dom'],
    official: true,
  },
  {
    id: 'css-tricks',
    title: 'CSS-Tricks',
    url: 'https://css-tricks.com/',
    description: 'Articles, guides, and references for CSS and layout techniques.',
    category: 'css',
    tags: ['css', 'layout'],
    official: false,
    featured: true,
  },
  {
    id: 'modern-css',
    title: 'Modern CSS Solutions',
    url: 'https://moderncss.dev/',
    description: 'Practical modern CSS patterns including container queries and subgrid.',
    category: 'css',
    tags: ['css', 'modern'],
    official: false,
  },
  {
    id: 'spec-css',
    title: 'CSS Specifications',
    url: 'https://www.w3.org/Style/CSS/specs.en.html',
    description: 'Official CSS specifications and working drafts from W3C.',
    category: 'css',
    tags: ['css', 'standards'],
    official: true,
  },
  {
    id: 'owasp',
    title: 'OWASP Web Security',
    url: 'https://owasp.org/www-project-web-security-testing-guide/',
    description: 'Web security testing guide and common vulnerability references.',
    category: 'security',
    tags: ['security', 'owasp'],
    official: true,
    featured: true,
  },
  {
    id: 'mdn-security',
    title: 'MDN Web Security',
    url: 'https://developer.mozilla.org/en-US/docs/Web/Security',
    description: 'Security concepts for the web platform including CSP, CORS, and HTTPS.',
    category: 'security',
    tags: ['security', 'documentation'],
    official: true,
  },
  {
    id: 'security-headers',
    title: 'securityheaders.com',
    url: 'https://securityheaders.com/',
    description: 'Analyze HTTP security response headers for a given site.',
    category: 'security',
    tags: ['security', 'headers', 'tool'],
    official: false,
  },
  {
    id: 'chrome-devtools',
    title: 'Chrome DevTools',
    url: 'https://developer.chrome.com/docs/devtools/',
    description: 'Documentation for Chrome developer tools: debugging, performance, network.',
    category: 'developer-tools',
    tags: ['devtools', 'chrome'],
    official: true,
    featured: true,
  },
  {
    id: 'firefox-devtools',
    title: 'Firefox Developer Tools',
    url: 'https://firefox-source-docs.mozilla.org/devtools-user/index.html',
    description: 'User documentation for Firefox built-in developer tools.',
    category: 'developer-tools',
    tags: ['devtools', 'firefox'],
    official: true,
  },
  {
    id: 'webhint',
    title: 'webhint',
    url: 'https://webhint.io/',
    description: 'Linting tool for the web: accessibility, performance, security hints.',
    category: 'developer-tools',
    tags: ['linting', 'tool'],
    official: false,
  },
];
